# Logistic Regression - Detection of Swallowing Disorders

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pandas import ExcelWriter
import os
import numpy as np
import random
plt.style.use("seaborn")
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sns
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

### Loading the dataset

In [2]:
healthy = pd.read_excel("D:/DATA SCIENCE/INTERNSHIP PROJECT/Modelling/HealthySamples.xlsx")
healthy = healthy[healthy["Sample status"] == "Perfect"]
healthy["Swallow_type"] = "healthy"
unhealthy = pd.read_excel("D:/DATA SCIENCE/INTERNSHIP PROJECT/Modelling/UnHealthySamples.xlsx")
unhealthy = unhealthy[unhealthy["Sample status"] == "Perfect"]
unhealthy["Swallow_type"] = "unhealthy"
data = healthy.append(unhealthy)[["Patient", "Sensor1_max", "Sensor2_max", "Sensor3_min", "Latency", "UES_start", "UES_end", "UES_Duration", "Swallow_type"]]
data["Label"] = np.where(data["Swallow_type"] == "healthy", 0, 1)
data

Patient  Sensor1_max  Sensor2_max  Sensor3_min  Latency  UES_start  \
0    Control 1.txt   192.279698   113.474479   -20.601968   -0.028   1552.752   
1    Control 1.txt   167.821012    98.336004   -11.776150   -0.028   1782.184   
2    Control 1.txt   171.739528   249.844358   -24.181735   -0.036    611.556   
3    Control 1.txt   200.377661   107.578393   -16.358434   -0.092   2333.764   
4    Control 1.txt   193.675898   105.770199   -25.335317   -0.172   1697.164   
..             ...          ...          ...          ...      ...        ...   
194      HD11A.txt   114.937700   101.913100   -27.384550    0.211    117.157   
195      HD11A.txt   195.568900    97.228870   -14.957330    0.200    163.116   
196      HD11A.txt   200.185000   116.615400    -9.014693   -0.042    124.009   
197      HD11B.txt   209.113400    79.385630   -12.359970    0.192     61.255   
201      HD11B.txt   309.871200    59.288520    -9.540810    0.110     10.308   

      UES_end  UES_Duration Swallow_type  Label  
0    1553.392         0.640      healthy      0  
1    1782.896         0.712      healthy      0  
2     612.284         0.728      healthy      0  
3    2334.412         0.648      healthy      0  
4    1697.784         0.620      healthy      0  
..        ...           ...          ...    ...  
194   117.828         0.671    unhealthy      1  
195   164.111         0.995    unhealthy      1  
196   124.538         0.529    unhealthy      1  
197    61.856         0.601    unhealthy      1  
201    10.866         0.558    unhealthy      1  

[244 rows x 10 columns]

In [3]:
unhealthy[["Sensor1_max", "Sensor2_max", "Sensor3_min", "Latency", "UES_Duration"]].describe()

Sensor1_max  Sensor2_max  Sensor3_min     Latency  UES_Duration
count   120.000000   120.000000   120.000000  120.000000    120.000000
mean    144.082960   145.538535   -13.641965    0.159658      0.814517
std      51.947881    79.275492     7.535588    0.103103      0.199220
min      80.756810    47.114770   -48.677570   -0.142000      0.420000
25%      98.738570    88.117125   -17.293390    0.104500      0.671000
50%     134.162300   127.453150   -12.117235    0.166500      0.786500
75%     170.505650   174.013475    -8.784615    0.217500      0.955000
max     309.871200   435.149900     1.642600    0.573000      1.601000

### Correlation matrix of Independent variables

In [4]:
corr = data[["Sensor1_max", "Sensor2_max", "Sensor3_min", "Latency", "UES_Duration"]].corr()
corr.style.background_gradient(cmap='coolwarm')

### Training and Test data split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(data[["Sensor1_max", "Sensor2_max", "Sensor3_min", "Latency", "UES_Duration"]], data[["Label"]], test_size=0.3, random_state=0)

### Composition of Training and test data

In [6]:
y_train.apply(pd.Series.value_counts)

Label
0     86
1     84

In [7]:
y_test.apply(pd.Series.value_counts)

Label
0     38
1     36

## Fitting a Logistic regression model

In [8]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

### Comparing Predicted and Actual values

In [9]:
y_pred = logreg.predict(X_test)

In [10]:
pred = pd.DataFrame(y_pred)
pred["Predicted"] = np.where(pred[0] == 0, "Healthy", "Unhealthy")
pred["Actual"] = np.where(y_test["Label"] == 0, "Healthy", "Unhealthy")
pred[["Predicted", "Actual"]]

Predicted     Actual
0     Healthy    Healthy
1     Healthy    Healthy
2     Healthy    Healthy
3     Healthy    Healthy
4   Unhealthy  Unhealthy
..        ...        ...
69  Unhealthy    Healthy
70    Healthy    Healthy
71  Unhealthy    Healthy
72  Unhealthy    Healthy
73    Healthy    Healthy

[74 rows x 2 columns]

### Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)
plt.figure(figsize = (7,7))
sns.set(font_scale=1.5)

[[24 14]
 [10 26]]


<Figure size 504x504 with 0 Axes>

### Model Evaluation metrics

In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.63      0.67        38
           1       0.65      0.72      0.68        36

    accuracy                           0.68        74
   macro avg       0.68      0.68      0.68        74
weighted avg       0.68      0.68      0.68        74



# Hyperparameter tuning in Logistic regression

## Evaluating best performing parameters

In [13]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
LRparam_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'penalty': ['l1','l2'],
    'max_iter': list(range(100,800,100)),
    'solver': ['liblinear', 'saga']
}

In [14]:
random_search = RandomizedSearchCV(logreg, param_distributions=LRparam_grid, cv=6, scoring="roc_auc")

In [15]:
random_search.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

RandomizedSearchCV(cv=6, error_score='raise-deprecating',
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='warn', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='warn', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='warn', n_iter=10, n_jobs=None,
                   param_distributions={'C': [0.001, 0.01, 0.1, 1, 10, 100,
                                              1000],
                                        'max_iter': [100, 200, 300, 400, 500,
                                                     600, 700],
 

In [16]:
random_search.best_estimator_

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='warn', n_jobs=None, penalty='l1',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

## Fitting a Logistic regression with best performing parameters

In [17]:
logreg = random_search.best_estimator_
logreg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='warn', n_jobs=None, penalty='l1',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

### Comparing Predicted and Actual values

In [18]:
y_pred = logreg.predict(X_test)

In [19]:
pred = pd.DataFrame(y_pred)
pred["Predicted"] = np.where(pred[0] == 0, "Healthy", "Unhealthy")
pred["Actual"] = np.where(y_test["Label"] == 0, "Healthy", "Unhealthy")
pred[["Predicted", "Actual"]]

Predicted     Actual
0     Healthy    Healthy
1     Healthy    Healthy
2     Healthy    Healthy
3     Healthy    Healthy
4   Unhealthy  Unhealthy
..        ...        ...
69  Unhealthy    Healthy
70    Healthy    Healthy
71  Unhealthy    Healthy
72  Unhealthy    Healthy
73    Healthy    Healthy

[74 rows x 2 columns]

## Recalculating Model Evaluation metrics for Model fitted with best performing parameters

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.61      0.65        38
           1       0.63      0.72      0.68        36

    accuracy                           0.66        74
   macro avg       0.67      0.66      0.66        74
weighted avg       0.67      0.66      0.66        74



In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)
plt.figure(figsize = (7,7))
sns.set(font_scale=1.5)

[[23 15]
 [10 26]]


<Figure size 504x504 with 0 Axes>

## Changing Probability threshold to achieve 100% detection of Unhealthy patients

In [22]:
THRESHOLD = 0.37
y_pred = np.where(logreg.predict_proba(X_test)[:,1] > THRESHOLD, 1, 0)

## Reevaluating Model Evaluation metrics with new threshold

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.21      0.35        38
           1       0.55      1.00      0.71        36

    accuracy                           0.59        74
   macro avg       0.77      0.61      0.53        74
weighted avg       0.78      0.59      0.52        74



In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)
plt.figure(figsize = (7,7))
sns.set(font_scale=1.5)

[[ 8 30]
 [ 0 36]]


<Figure size 504x504 with 0 Axes>